### ISSUE TITLE
Remove -ffast-math from linker flags

### ISSUE THREAD

**Issue by isuruf** [latte-int/latte#12]
Adding -ffast-math in linker command would link in startup files that would change the FPU control bits globally and would affect any library run that is loaded along with `liblatte.so`. For eg: denormalized numbers would be flushed to zero in python if python loads `liblatte.so`.

**Comment by mkoeppe** [comment]
Thanks. Removed in ebea030e870bfccd45c4a26c1329b848d58e9dc3
