### ISSUE TITLE
Find cddlib headers in new upstream install location

### ISSUE THREAD

**Issue by mkoeppe** [latte-int/latte#15]
https://github.com/cddlib/cddlib/pull/38

**Comment by kliem** [comment]
I have opened #23, which might be an easier approach to supporting the new headers location.

**Comment by kliem** [comment]
Ok, maybe this is a stupid question, but how do I obtain something as `latte-int-1.7.5.tar.gz` to test this locally? Just the source code won't work in sage.

**Comment by kliem** [comment]
Found a workaround, just modified `latte-int-1.7.5.tar.gz` itself.

**Comment by mkoeppe** [comment]
> how do I obtain something as `latte-int-1.7.5.tar.gz` to test this locally?

`./autogen.sh && ./configure && make dist`

**Comment by mkoeppe** [comment]
Fixed in `master`. Thanks @kliem @jengelh for your patches
