### ISSUE TITLE
Latte-int checks for topcom executable but it is not listed in the README

### ISSUE THREAD

**Issue by kiwifb** [latte-int/latte#22]
```
checking for points2triangs... /usr/bin/points2triangs
checking for points2placingtriang... /usr/bin/points2placingtriang
```
those are topcom commands. The README should mention whether they are mandatory or optional.

**Comment by mkoeppe** [comment]
They are optional - otherwise configure would exit with an error.

**Comment by kiwifb** [comment]
I am arguing that. I am arguing that the README mention the other optional packages but not this one. I am arguing about incomplete documentation.

**Comment by mkoeppe** [comment]
Added to the README in 03e8b7881b0d43345d1a8d219a870559f6b87a1e. Thanks!
