### ISSUE TITLE
header in code/latte/sqlite/ are not shipped in the released tarball

### ISSUE THREAD

**Issue by kiwifb** [latte-int/latte#31]
I am guessing it is not a big deal because that stuff does not seem to be used/compiled at the moment.

So, I was busy making a new ebuild of latte-int for Gentoo that includes the commit 6dbf7f07d5c9e1f3afe793f782d191d4465088ae to fix issue #24. And then the patch failed because it could not find the file `code/latte/sqlite/IntegrationDB.h` to patch. And it could not find the file because it is not in the tarball for 1.7.6 that I am downloading here.

**Comment by mkoeppe** [comment]
I think leaving this code out from the tarball was the intention. This is just special purpose code that we needed for computations in a paper.

I did mess up https://trac.sagemath.org/ticket/33981, which broke that latte build in Sage...

**Comment by kiwifb** [comment]
I do warn people against doing that kind of mixing up "professionally" (I guess that's one of the thing I am actually paid for). But I had a feel that the whole folder did not belong.

**Comment by mkoeppe** [comment]
Did I mention there used to be a > 4GB database blob in the repo that I had to surgically remove at some point?

**Comment by kiwifb** [comment]
> Did I mention there used to be a > 4GB database blob in the repo that I had to surgically remove at some point?

"I am not sure I want to know" is my standard answer to that kind of things.
